NRI課題　HTMLコーディング
nakadasatoshi/quelcode-html pull request #1
Opened 2020-07-31 06:31 UTC by nakadasatoshi

初回の提出です。レビューよろしくお願いします。

2020-07-31 06:45 UTC, piasoratech requested changes
提出ありがとうございます！
いくつか指摘事項があるので１つずつ確認して修正していってください！

- 提出ファイルに画像を含めるようにしてください
- インデントが全体的にそろっていないので、そろえるよう調整してください
- コード内で指摘した事項は他の部分でも同様に言える場合があるので再提出の際には全体的によく確認したうえで提出をお願いします

2020-07-31 06:45 UTC, piasoratech commented on nri/index.html
> +      <meta charset="UTF-8">
今回`meta`タグは`description`も設定するようにしてください

2020-07-31 06:45 UTC, piasoratech commented on nri/index.html
> +            <h1 class="header-logo"><a href="#"><img src="images/nri-logo.png" alt="NRIのロゴ"></a></h1>
ここはあくまでロゴなので見出しとは違うかと思います。
hタグを外しましょう

2020-07-31 06:45 UTC, piasoratech commented on nri/index.html
> +                       <div></div>
今回ハンバーガーメニューを実装しない場合はアイコンを画像として表示していただくだけで大丈夫です！

2020-07-31 06:45 UTC, piasoratech commented on nri/index.html
> +            <p><a href="#">NRIトップ&nbsp;&gt;</a>&nbsp;<a href="#">企業情報&nbsp;&gt;</a>&nbsp;<a>NRIの強み：NIRのデジタルビジネス戦略</a></p>
`>`この記号は直接書き込むのではなく、疑似要素などで後でつけるようにしましょう

2020-07-31 06:45 UTC, piasoratech commented on nri/index.html
> +                <a>Share</a>
リンクではないので`a`タグではないですね

2020-07-31 06:45 UTC, piasoratech commented on nri/index.html
> +          <div class="end">
footer始めるなら文章構造的にここからが良いかと思います。

2020-08-03 08:56 UTC, ghost reviewed
コメント入れました。

2020-08-03 09:06 UTC, ghost reviewed
修正不要のコメントを1件入れました。

2020-08-05 05:30 UTC, nakadasatoshi commented
ありがとうございます

2020-08-05 05:30 UTC, merged